# Generated by Django 5.0.4 on 2024-04-09 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(default='default_profile.jpg', upload_to='profile_pics', verbose_name='Profile Picture')),
                ('user_bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone Number')),
                ('wanna_be_a_blogger', models.BooleanField(blank=True, default=False, null=True, verbose_name='Wanna be a Blogger?')),
                ('user_company', models.CharField(blank=True, max_length=100, null=True, verbose_name=' Your Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Person Model',
            },
        ),
    ]
