# Generated by Django 5.0.4 on 2024-04-13 12:25

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel'), ('Sports', 'Sports'), ('Music', 'Music'), ('Movies', 'Movies'), ('Books', 'Books'), ('Fitness', 'Fitness'), ('Business', 'Business'), ('Politics', 'Politics'), ('Science', 'Science'), ('Art', 'Art'), ('Education', 'Education'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], default='Technology', max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('image', models.ImageField(default='default_blog.jpg', upload_to='blog_pics', verbose_name='Blog Image')),
                ('date_posted', models.DateField(auto_now_add=True, null=True, verbose_name='Date Posted')),
                ('last_updated', models.DateField(auto_now=True, null=True, verbose_name='Last Updated')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_blogs', to='accounts.person')),
                ('category', models.ManyToManyField(related_name='blog_categories', to='blogApp.blogcategory')),
            ],
            options={
                'verbose_name_plural': 'Blog Models',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('date_commented', models.DateTimeField(auto_now_add=True, verbose_name='Date Commented')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_blog', to='blogApp.blogmodel')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_person', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(choices=[(-1, 'Dislike'), (0, 'No Reaction'), (1, 'Like')], default=0)),
                ('date_reacted', models.DateTimeField(auto_now=True, verbose_name='Date Reacted')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blogApp.blogmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaction Model',
                'unique_together': {('user', 'blog')},
            },
        ),
    ]
